version: "3"

services:
  db:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: explorer_api
    ports:
      - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
      - db
    environment:
      - DB_USERNAME=root
      - DB_NAME=explorer_api
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=root
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: polkascan/explorer-api-beta
    command: bash -c "/usr/src/start-api.sh"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_USERNAME=root
      - DB_NAME=explorer_api
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=root
