version: "3"

services:
  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
    environment:
      - DB_USERNAME=matthijs
      - DB_NAME=polkascan_v1_rococo
      - DB_HOST=qnap-11
      - DB_PORT=36001
      - DB_PASSWORD=matthijs
      - POLLING_REDIS_HOST=redis
      - POLLING_REDIS_PORT=6379

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: polkascan/explorer-api-beta
    command: bash -c "/usr/src/start-api.sh"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DB_USERNAME=matthijs
      - DB_NAME=polkascan_v1_rococo
      - DB_HOST=qnap-11
      - DB_PORT=36001
      - DB_PASSWORD=matthijs
